let container = document.getElementById("imgGif");
let PhotoList = ["CLC/OT7 5.jpg",
"CLC/OT7 3.jpg",
"CLC/OT7 Devil.jpg",
"CLC/OT7.jpg",
"CLC/OT7 2.jpg",
"CLC/OT7 Devil 2.jpg",
"CLC/OT7 Black Dress.jpg",
"CLC/OT7 Helicopter.jpg",
"CLC/Sorn blond avocado.png",
"CLC/Sorn blond discord profile picture.jpg",
"CLC/Sorn Blond Hair 2.jpg",
"CLC/Sorn Blond Hair.png",
"CLC/Sorn Brown Hair 2.jpg",
"CLC/Sorn Blond Hair 3.jpg",
"CLC/Sorn Blond Hair 4.jpg",
"CLC/Sorn Brown Hair.jpg",
"CLC/Sorn Brown Hair 3.jpg",
"CLC/Sorn Brown Hair 4.jpg",
"CLC/Sorn devil.jpg",
"CLC/Sorn tiktok.jpg",
"CLC/Sorn.jpg",
"CLC/Sorn Black Dress.jpg",
"CLC/Sorn Cute.jpg",
"CLC/Sorn Cute 2.jpg",
"CLC/Sorn Cute 3.jpg",
"CLC/Sorn Cute 4.jpg",
"CLC/Sorn Devil 2.jpg",
"CLC/Sorn Blond Hair 6.jpg",
"CLC/Sorn Blond Hair 7.jpg",
"CLC/Sorn Blond Hair 8.jpg",
"CLC/Sorn Blond Hair 9.jpg",
"CLC/Sorn 2.jpg",
"CLC/Sorn Watermelon.jpg",
"CLC/Sorn Helicopter 2.jpg",
"CLC/Sorn Crown.jpg",
"CLC/Yujin Helicopter.jpg",
"CLC/Yujin Black Dress.jpg",
"CLC/Yujin.jpg",
"CLC/Yujin Devil.jpg",
"CLC/Yeeun Helicopter.jpg",
"CLC/Yeeun.jpg",
"CLC/Yeeun Devil.jpg",
"CLC/Yeeun Black Dress.jpg",
"CLC/Seunghee Helicopter.jpg",
"CLC/Seunghee.jpg",
"CLC/Seunghee Devil.jpg",
"CLC/Seunghee Black Dress.jpg",
"CLC/Eunbin Helicopter.jpg",
"CLC/Eunbin.jpg",
"CLC/Eunbin Devil.jpg",
"CLC/Eunbin Black Dress.jpg",
"CLC/Seungyeon Helicopter.jpg",
"CLC/Seungyeon.jpg",
"CLC/Seungyeon Devil.jpg",
"CLC/Seungyeon Black Dress.jpg",
"CLC/Elkie Helicopter.jpg",
"CLC/Elkie.jpg",
"CLC/Elkie Devil.jpg",
"CLC/Elkie Black Dress.jpg",
"DREAMCATCHER/OT6 EN.jpg",
"DREAMCATCHER/OT6.jpg",
"DREAMCATCHER/OT6 2.jpg",
"DREAMCATCHER/OT7 2.jpg",
"DREAMCATCHER/OT7 3.jpg",
"DREAMCATCHER/OT7 5.jpg",
"DREAMCATCHER/Dami.jpg",
"DREAMCATCHER/Dami 2.jpg",
"DREAMCATCHER/Dami 3.jpg",
"DREAMCATCHER/Dami EN.jpg",
"DREAMCATCHER/Dami 6.jpg",
"DREAMCATCHER/Dami 5.jpg",
"DREAMCATCHER/Dami 7.jpg",
"DREAMCATCHER/Dami 8.jpg",
"DREAMCATCHER/Dami 9.jpg",
"DREAMCATCHER/Gahyeon.jpg",
"DREAMCATCHER/Gahyeon 2.jpg",
"DREAMCATCHER/Gahyeon 3.jpg",
"DREAMCATCHER/Gahyeon EN.jpg",
"DREAMCATCHER/Gahyeon 4.jpg",
"DREAMCATCHER/Gahyeon 5.jpg",
"DREAMCATCHER/SuA.jpg",
"DREAMCATCHER/SuA 2.jpg",
"DREAMCATCHER/SuA 3.jpg",
"DREAMCATCHER/SuA EN.jpg",
"DREAMCATCHER/SuA 4.jpg",
"DREAMCATCHER/SuA 5.jpg",
"DREAMCATCHER/Handong.jpg",
"DREAMCATCHER/Handong 2.jpg",
"DREAMCATCHER/Handong 3.jpg",
"DREAMCATCHER/JiU.jpg",
"DREAMCATCHER/JiU 2.jpg",
"DREAMCATCHER/JiU 3.jpg",
"DREAMCATCHER/JiU EN.jpg",
"DREAMCATCHER/JiU 4.jpg",
"DREAMCATCHER/JiU 5.jpg",
"DREAMCATCHER/Siyeon.jpg",
"DREAMCATCHER/Siyeon 2.jpg",
"DREAMCATCHER/Siyeon 3.jpg",
"DREAMCATCHER/Siyeon 5.jpg",
"DREAMCATCHER/Siyeon EN.jpg",
"DREAMCATCHER/Siyeon 4.jpg",
"DREAMCATCHER/Yoohyeon.jpg",
"DREAMCATCHER/Yoohyeon 2.jpg",
"DREAMCATCHER/Yoohyeon 3.jpg",
"DREAMCATCHER/Yoohyeon EN.jpg",
"DREAMCATCHER/Yoohyeon 4.jpg",
"DREAMCATCHER/Yoohyeon 5.jpg",
"ONEUS/ONEUS suit.jpg",
"ONEUS/OT6 IIT.jpg",
"ONEUS/OT6 Devil.jpg",
"ONEUS/OT6 Binary Code.jpg",
"ONEUS/OT6 Binary Code 2.jpg",
"ONEUS/OT6 Lived.jpg",
"ONEUS/OT6 ASWE.jpg",
"ONEUS/OT6 Devil 2.png",
"ONEUS/OT6 Binary Code 3.jpg",
"ONEUS/OT6 FanMeeting.jpg",
"ONEUS/OT6 outside.jpg",
"ONEUS/OT6 Banbakburga.jpeg",
"ONEUS/OT6 Bbusyeo.jpg",
"ONEUS/RavN Keonhee Bbusyeo.jpg",
"ONEUS/OT6 Bbusyeo 2.jpg",
"ONEUS/OT6 Bbusyeo 3.jpg",
"ONEUS/OT6 Bbusyeo 4.jpg",
"ONEUS/RavN Twilight.jpeg",
"ONEUS/RavN Lived.jpg",
"ONEUS/RavN Lit.jpg",
"ONEUS/RavN Lit 2.jpg",
"ONEUS/RavN Brown hair plush.png",
"ONEUS/RavN Devil.jpeg",
"ONEUS/RavN IIT.jpg",
"ONEUS/RavN Lived 2.jpg",
"ONEUS/RavN BC.jpg",
"ONEUS/RavN.jpeg",
"ONEUS/RavN Bbusyeo.jpg",
"ONEUS/RavN 2.jpg",
"ONEUS/Hwanwoong BC.jpg",
"ONEUS/Hwanwoong Devil.jpeg",
"ONEUS/Hwanwoong IIT.jpg",
"ONEUS/Hwanwoong Lived.jpg",
"ONEUS/Hwanwoong Bbusyeo.jpg",
"ONEUS/Hwanwoong FanMeeting.jpg",
"ONEUS/Xion BC.jpg",
"ONEUS/Xion FanMeeting.jpg",
"ONEUS/Xion Devil.jpg",
"ONEUS/Xion IIT.jpg",
"ONEUS/Xion Lived.jpg",
"ONEUS/Xion Bbusyeo 2.jpg",
"ONEUS/Xion Bbusyeo 3.jpg",
"ONEUS/Xion Bbusyeo.jpg",
"ONEUS/Xion Bbusyeo 4.jpg",
"ONEUS/Seoho BC.jpg",
"ONEUS/Seoho Devil.jpeg",
"ONEUS/Seoho Devil 2.jpg",
"ONEUS/Seoho IIT.jpg",
"ONEUS/Seoho Lived.jpg",
"ONEUS/Seoho FanMeeting.jpg",
"ONEUS/Leedo BC.jpg",
"ONEUS/Leedo Devil.jpeg",
"ONEUS/Leedo IIT.jpg",
"ONEUS/Leedo Lived.jpg",
"ONEUS/Leedo FanMeeting.jpg",
"ONEUS/Leedo Bbusyeo.jpg",
"ONEUS/Keonhee BC.jpeg",
"ONEUS/Keonhee Devil.jpg",
"ONEUS/Keonhee Devil 2.jpg",
"ONEUS/Keonhee IIT.jpg",
"ONEUS/Keonhee Lived.jpg",
"ONEUS/Keonhee FanMeeting.jpg",
"P1H/OT6 Breakthrough.jpg",
"P1H/OT6 Siren 2.jpg",
"P1H/P1H OT6 2.jpg",
"P1H/P1H OT6.jpg",
"P1H/OT6 Siren.jpg",
"P1H/OT6.jpg",
"P1H/OT6 debut.jpg",
"P1H/Intak 3.jpg",
"P1H/Intak 4.jpg",
"P1H/Intak 2.jpg",
"P1H/Intak Breakthrough.jpg",
"P1H/Intak Siren.jpg",
"P1H/Intak.jpg",
"P1H/Jiung 3.jpg",
"P1H/Jiung 4.jpg",
"P1H/Jiung 2.jpg",
"P1H/Jiung Breakthrough.jpg",
"P1H/Jiung Siren.jpg",
"P1H/Jiung.jpg",
"P1H/Jongseob 6.jpg",
"P1H/Jongseob 7.jpg",
"P1H/Jongseob 2.jpg",
"P1H/Jongseob 3.jpg",
"P1H/Jongseob 4.jpg",
"P1H/Jongseob 5.jpg",
"P1H/Jongseob Breakthrough.jpg",
"P1H/Jongseob Siren.png",
"P1H/Jongseob.jpg",
"P1H/Keeho 3.jpg",
"P1H/Keeho 4.jpg",
"P1H/Keeho 2.jpg",
"P1H/Keeho Siren.jpg",
"P1H/Keeho.jpg",
"P1H/Soul 3.jpg",
"P1H/Soul 2.jpg",
"P1H/Soul Breakthrough.jpg",
"P1H/Soul Siren 2.jpg",
"P1H/Soul Siren.jpg",
"P1H/Soul.jpg",
"P1H/Theo 3.jpg",
"P1H/Theo Breakthrough.jpg",
"P1H/Theo Siren 2.jpg",
"P1H/Theo Siren.jpg",
"P1H/Theo.jpg",
"RCPC/RCPC OT6 ringring.jpg",
"RCPC/OT6 ringring 2.jpg",
"RCPC/OT6 Blue punch.jpg",
"RCPC/OT6 Juicy.jpg",
"RCPC/Sohee blond.jpg",
"RCPC/Sohee blue punch.jpg",
"RCPC/Sohee brown hair.jpg",
"RCPC/Sohee glasses.png",
"RCPC/Sohee ringring 2.jpg",
"RCPC/Yunkyoung 2.jpg",
"RCPC/yunkyoung blond.jpg",
"RCPC/Yunkyoung blue punch.jpg",
"RCPC/Yunkyoung blue punch 2.jpg",
"RCPC/yunkyoung red hair.jpg",
"RCPC/YunkYoung.jpg",
"RCPC/Yunkyoung ringring 2.jpg",
"RCPC/Juri ringring.jpg",
"RCPC/Juri ringring 2.jpg",
"RCPC/Juri blue punch.jpg",
"RCPC/Juri blue punch 2.jpg",
"RCPC/Dahyun ringring.jpg",
"RCPC/Dahyun ringring 2.jpg",
"RCPC/Dahyun blue punch.jpg",
"RCPC/Dahyun blue punch 2.jpg",
"RCPC/Suyun ringring.jpg",
"RCPC/Suyun ringring 2.jpg",
"RCPC/Suyun blue punch.jpg",
"RCPC/Suyun blue punch 2.jpg",
"RCPC/Yeonhee ringring.jpg",
"RCPC/Yeonhee ringring 2.jpg",
"RCPC/Yeonhee blue punch.jpg",
"RCPC/Yeonhee blue punch 2.jpg",
];

let r = Math.floor(Math.random()*PhotoList.length);
container.innerHTML = "<img id=\"imgGifContent\" src=\"../" + PhotoList[r] + "\"/>";

function clickGif() {
r++;
if (r > PhotoList.length) {
    r = 0;
}
container.innerHTML = "<img id=\"imgGifContent\" src=\"../" + PhotoList[r] + "\"/>";
}

const i = setInterval(clickGif, 10000);
